// <auto-generated />
using System;
using CloudUsage.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudUsage.Api.Data.Migrations
{
    [DbContext(typeof(UsageAnalyticsDbContext))]
    partial class UsageAnalyticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CloudUsage.Api.Data.Entities.RawUsageEvent", b =>
                {
                    b.Property<long>("RawEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("raw_event_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RawEventId"));

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("IngestionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("ingestion_status");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("product_code");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("properties_json");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("UserExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("user_external_id");

                    b.HasKey("RawEventId");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("UX_raw_usage_event_event_id");

                    b.HasIndex("IngestionStatus", "ReceivedAtUtc")
                        .HasDatabaseName("IX_raw_usage_event_status_received_at");

                    b.ToTable("raw_usage_event", null, t =>
                        {
                            t.HasCheckConstraint("CK_raw_usage_event_properties_json", "[properties_json] IS NULL OR ISJSON([properties_json]) = 1");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
